version: '3'

services:
  iot-dashboard:
    image: arville27/iot-dashboard
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      - INFLUXDB_URL=http://localhost:8086
      - INFLUXDB_TOKEN=sadsad
      - INFLUXDB_BUCKET=guest-visit
      - INFLUXDB_ORG=personal